[package]
name = "anobe"
version = "0.4.0"
description = "Anobe — app hub to install, manage and bridge Adobe alternatives"
authors = ["Anobe Contributors"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = { version = "0.25", default-features = false, features = ["png"] }
url = "2"
tauri-plugin-log = "2.9.1"
tauri-plugin-os = "2.3.2"
tauri-plugin-deep-link = "2.4.10"
log = "0.4"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2.4.4"
tauri-plugin-window-state = "2"
